FROM node:22-alpine

RUN apk add --no-cache python3 make g++
RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml ./

COPY .husky ./.husky

RUN pnpm install

RUN npm rebuild better-sqlite3

COPY . .

RUN mkdir -p .data

EXPOSE 5173

CMD ["pnpm", "dev", "--", "--host"]